services:
  async-api:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: async-apservice
    ports:
      - "8082:8082"
    networks:
      - signoz-network

  postgres:
    image: postgres:17
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: async
    ports:
      - "5432:5432"
    networks:
      - signoz-network

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - signoz-network

networks:
  signoz-network:
    external: true