spring:
  application:
    name: async-service
  cloud:
    function:
      definition: userConsumer
    stream:
      bindings:
        userConsumer-in-0:
          destination: user
          contentType: application/json
        user-out-0:
          destination: user
          contentType: application/json
      kafka:
        binder:
          brokers: kafka:9092
          autoCreateTopics: true
  datasource:
    url: jdbc:postgresql://postgres:5432/async
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: mailpit
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8082
